import Head from "next/head"; 
import styles from "../styles/Home.module.css";
import { FirstCard } from "../src/Cards/firstCard"
import { SecondCard } from "../src/Cards/secondCard"
import { ThirdCard } from "../src/Cards/thirdCard"
import { useState } from "react";

export default function Home() {

  const [value, setValue] = useState('');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,500;0,600;0,700;1,400&display=swap" rel="stylesheet" />
      </Head>
      <main className={styles.main}>
        <div className={styles.title}>Curver</div>
        <div className={styles.subtitle}>By Ben Ostrovsky & Léo Mindlin </div>

        <div className={styles.cardContainer}>
          <FirstCard></FirstCard>
          <SecondCard></SecondCard>
          <ThirdCard></ThirdCard>
        </div>
      </main>
    </>
  );
}